# Generated by Django 4.2.6 on 2023-10-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalam', '0002_alter_coffeesesion_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeesesion',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
