# Generated by Django 4.2.6 on 2023-10-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalam', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
