# Generated by Django 4.1.7 on 2023-10-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalam', '0005_alter_booking_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeesesion',
            name='img',
            field=models.ImageField(default=1, upload_to='coffee/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coffeesesion',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
